Find the hostname for SNI regardless of case used in `request_headers`
cdent/gabbi pull request #316
Opened 2022-08-16 18:01 UTC by scottwallacesh

This change ensures that the hostname needed for SNI can be found regardless of the case used for the keys in `request_headers`.

2022-08-16 18:24 UTC, cdent commented
I think this is fine as a fix, but it does make me wonder if we should canonicalise the header names when reading in the tests.

Any thoughts on that?

The reason it occurs to me is because I've been working on a [golang version](https://github.com/cdent/gobbi) and go's libraries do a similar kind of canonicalisation.

I've resisted it in the past for people who for some reason actually do want to test sending a header with weird case and now that the precedent is set, changing it would be odd.

I'm happy to merge this (and do a new release) once the pep8 issue is resolved.

2022-08-16 18:24 UTC, cdent requested changes

2022-08-16 18:55 UTC, scottwallacesh commented
> I think this is fine as a fix, but it does make me wonder if we should canonicalise the header names when reading in the tests.
> 
> Any thoughts on that?

The RFCs for HTTP say the headers should be case-insensitive, so I'm inclined to agree that they should be canonicalised but I'm also aware of breaking other people's tests.  If you're migrating to a Go-based version then I would leave the Python version as-is for now unless there are other more important reasons why they should be canonicalised.

2022-08-16 18:55 UTC, scottwallacesh commented on gabbi/suitemaker.py
> +            key.lower(): val for key, val in test.get('request_headers', {}).items()
Fixed.

2022-08-17 06:53 UTC, FND commented
I agree that header normalization would be desirable, but backwards compatibility trumps that now. We might introduce some kinda opt-in mechanisms, but this seems too arcane to warrant user choice.

FWIW, my first instinct with the dictionary comprehension was "this seems very roundabout and not very Pythonic" (I didn't grok right away what was happening there) - only to realize there's probably no more straightforward or efficient alternative. However, it did [lead me](https://stackoverflow.com/a/16817943) to [Requests's `CaseInsensitiveDict`](https://github.com/kennethreitz/requests/blob/3bb13f8fbb9d4ed1a20bd33495cdc087eb062ca0/requests/structures.py#L37); might be handy if we do go with normalization at some point.

2022-08-17 07:14 UTC, scottwallacesh commented
I'm not entirely sure what to do about the current broken test as it doesn't appear to have been caused by this change. I don't have Python 3.7 on my machine and can't test it locally.

Any suggestions? Should I attempt to fix it or is it a known issue that can be safely ignored?

2022-08-17 08:57 UTC, cdent commented
> If you're migrating to a Go-based version

It's not so much a migration as playing around to see what's possible and if there are any advantages. If it works out I don't intend to abandon gabbi in favour of gobbi or anything like that.

Note that we probably already has case-insensitivity for evaluating response-headers. It's in the send of request headers where we do not, and may not want to, have it.

The placement 3.7 tests failing is something in placement itself. I'll fix that separately. Once that's done this should be good to go.

2022-08-17 09:16 UTC, merged

2022-08-17 09:50 UTC, cdent commented
2.7.2 is on pypi now https://pypi.org/project/gabbi/